<?xml version="1.0"?>
<robot xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
    xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
    xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
    xmlns:xacro="http://ros.org/wiki/xacro"
    name="tinker">

    <xacro:include filename="./base.gazebo.xacro" />
    <xacro:include filename="../sensor/hokuyo_lx30_laser.urdf.xacro" />
    <xacro:include filename="../materials.xacro" />


    <xacro:property name="PI" value="3.1415926535897931"/>

    <xacro:property name="base_mass" value="1"/>
    <xacro:property name="base_length" value="0.64"/>
    <xacro:property name="base_width" value="0.52"/>
    <xacro:property name="base_height" value="0.15"/>

    <xacro:property name="base_laser_x" value="0.30"/>
    <xacro:property name="base_laser_y" value="0"/>
    <xacro:property name="base_laser_z" value="0.185"/>

    <xacro:property name="kinect_x" value="0"/>
    <xacro:property name="kinect_y" value="0.20"/>
    <xacro:property name="kinect_z" value="1.26"/>

    <xacro:property name="arm_origin_x" value="0.12"/>
    <xacro:property name="arm_origin_y" value="0"/>
    <xacro:property name="arm_origin_z" value="0.77"/>

    <xacro:property name="wheel_mass" value="1"/>


<!--*****************chasiss***********************-->
  <link name="base_link">
      <visual>
          <geometry>
              <box size="${base_length} ${base_width} ${base_height}"/>
          </geometry>
          <origin xyz="0 0 ${base_height/2}" />
          <material name="white">
          </material>
      </visual>

      <collision>
          <geometry>
              <box size="${base_length} ${base_width} ${base_height}"/>
          </geometry>
          <origin xyz="0 0 ${base_height/2}" />
      </collision>

      <inertial>
          <origin xyz="0 0 ${base_height/2}" />
          <mass value="${base_mass}"/>
          <inertia
              ixx="${base_mass / 12.0 * (base_length * base_width + base_height * base_height)}" ixy="0.0" ixz="0.0"
              iyy="${base_mass / 12.0 * (base_height * base_height + base_length * base_width)}" iyz="0.0"
              izz="${base_mass / 12.0 * (base_length * base_width + base_length * base_width)}"/>
      </inertial>
  </link>

  <xacro:hokuyo_lx30_laser_v0 name="base_laser" parent="base" ros_topic="scan" update_rate="20" min_angle="${-3*PI/4}" max_angle="${3*PI/4}" >
      <origin xyz="${base_laser_x} ${base_laser_y} ${base_laser_z}" rpy="0 0 0" />
  </xacro:hokuyo_lx30_laser_v0>


<!--*****************base_to_arm_platform***********************-->
    <link name="kinect_link" />
    <link name="arm_link" />
    <joint name="kinect_joint" type="fixed">
        <parent link="base_link" />
        <child link="kinect_link" />
        <origin xyz="${kinect_x} ${kinect_y} ${kinect_z}" rpy="0 0 0" />
    </joint>
    <joint name="arm_origin_joint" type="fixed">
        <parent link="base_link" />
        <child link="arm_link" />
        <origin xyz="${arm_origin_x} ${arm_origin_y} ${arm_origin_z}" rpy="0 0 0" />
    </joint>
</robot>
